mysql:
  # the final connection string looks like this:
  # Server={serverIp};Port={port};Database={databaseName};{Uid=username};Pwd={password}
  serverIp: ""
  port: 0
  databaseName: ""
  username: ""
  password: ""
discord:
  # prefix for commands (e.g. <prefix>pending (e.g. !pending))
  prefix: ""
  # discord bot token (obtainable at discordapp.com/developers)
  token: "" 
  channelNames:
    # put in all channel names without '#'
    # the name of the channel with the player apps (e.g. #member-apps) (not the staff spam channel)
    memberApps: ""
    # the name of the channel to which member-bot will send polychat commands
    polychat: ""
